# -*- coding: utf-8 -*-
"""
/***************************************************************************
 nl_wfs_loader
                                 A QGIS plugin
 Deze plugin laad publiek beschikbare, maar lastig vindbare, WFS lagen.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-03
        copyright            : (C) 2025 by T.  de Jong
        email                : taco@tictaco.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


from .nl_wfs_loader import NLWFSLoader

def classFactory(iface):
    return NLWFSLoader(iface)
